name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poppler
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Install Python package dependencies
        run: pip3 install -r requirements.txt

      - name: Run the tests
        env:
          NODE_OPTIONS: --no-warnings
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: python pdfTester.py --api-key ${{ secrets.APPLITOOLS_API_KEY }} --pdf-folder "./pdfs" --app-name "applitools_pdftester_python"
