name: Updates

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: pip install pur

      - name: Check for Updates
        run: pur -r requirements.txt

      - name: Install Updates
        run: pip install -r requirements.txt

      - name: Run the test
        run: pytest tutorial.py

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master'
